=== EloyMariscalFernandez/sew/LaVuelta2026/xml/etapa.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.uniovi.es"
	xmlns="http://www.uniovi.es"
	elementFormDefault="qualified">

	<xs:element name="Etapa">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre" />
				<xs:element ref="numero" />
				<xs:element ref="datosCircuito" />
				<xs:element ref="datosParticipantes" />
				<xs:element ref="ReferenciasLocalidades" />
				<xs:element ref="fotografias" />
				<xs:element ref="videos" />
				<xs:element ref="audios" />
				<xs:element ref="lugares" />
				<xs:element ref="hitos" />
				<xs:element ref="puntosAnonimos" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="nombre" type="xs:string" />
	<xs:element name="numero" >
		<xs:simpleType>
			<xs:restriction base="xs:nonNegativeInteger">
                <xs:minInclusive value="1"/>
                <xs:maxInclusive value="21"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

	<xs:element name="datosCircuito">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="distancia" />
				<xs:element ref="fecha" />
				<xs:element ref="desnivel" />
				<xs:element ref="tipo" />
				<xs:element ref="Empieza" />
				<xs:element ref="Acaba" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="distancia">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:decimal">
					<xs:attribute name="unidades" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="fecha" type="xs:date" />

	<xs:element name="desnivel">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="distanciaPositivaType">
					<xs:attribute name="unidades" type="xs:string" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="tipo" type="xs:string" />
	<xs:element name="Empieza" type="xs:string" />
	<xs:element name="Acaba" type="xs:string" />

	<xs:element name="datosParticipantes">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="tiempoGanador" />
				<xs:element ref="velocidadMedia" />
				<xs:element ref="lideresCarrera" />
				<xs:element ref="lideresGeneral" />
				<xs:element ref="lideresEquipos" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="tiempoGanador" type="xs:duration" />

	<xs:element name="velocidadMedia">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:float">
					<xs:attribute name="unidades" type="xs:string" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="lideresCarrera">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="primero" />
				<xs:element ref="segundo" />
				<xs:element ref="tercero" />
				<xs:element ref="tiempoEntrePrimero-segundo" />
				<xs:element ref="tiempoEntrePrimero-tercero" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="lideresGeneral">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="primero" />
				<xs:element ref="segundo" />
				<xs:element ref="tercero" />
				<xs:element ref="tiempoEntrePrimero-segundo" />
				<xs:element ref="tiempoEntrePrimero-tercero" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="lideresEquipos">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="primero" />
				<xs:element ref="segundo" />
				<xs:element ref="tercero" />
				<xs:element ref="tiempoEntrePrimero-segundo" />
				<xs:element ref="tiempoEntrePrimero-tercero" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="primero" type="xs:string" />
	<xs:element name="segundo" type="xs:string" />
	<xs:element name="tercero" type="xs:string" />
	<xs:element name="tiempoEntrePrimero-segundo" type="xs:duration" />
	<xs:element name="tiempoEntrePrimero-tercero" type="xs:duration" />

	<!-- Referencias a Localidades -->
	<xs:element name="ReferenciasLocalidades">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" minOccurs="1" ref="ref" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ref" type="xs:anyURI" />

	<!-- Fotografías, Vídeos y Audios -->
	<xs:element name="fotografias">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="5" minOccurs="1" ref="foto" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="foto" type="xs:anyURI" />

	<xs:element name="videos">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="3" minOccurs="1" ref="video" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="video" type="xs:anyURI" />

	<xs:element name="audios">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="3" minOccurs="1" ref="audio" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="audio" type="xs:anyURI" />

	<!-- Lugares (Salida y Llegada) -->
	<xs:element name="lugares">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="salidaLong" />
				<xs:element ref="salidaLat" />
				<xs:element ref="salidaAlt" />
				<xs:element ref="llegadaLong" />
				<xs:element ref="llegadaLat" />
				<xs:element ref="llegadaAlt" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

    <xs:simpleType name="longitudRangoType">
        <xs:restriction base="xs:decimal">
            <xs:minInclusive value="-180.0"/>
            <xs:maxInclusive value="180.0"/>
        </xs:restriction>
    </xs:simpleType>

	<xs:simpleType name="latitudRangoType">
        <xs:restriction base="xs:decimal">
            <xs:minInclusive value="-90.0"/>
            <xs:maxInclusive value="90.0"/>
        </xs:restriction>
    </xs:simpleType>

	<xs:simpleType name="distanciaPositivaType">
        <xs:restriction base="xs:decimal">
            <xs:minInclusive value="0.0"/>
        </xs:restriction>
    </xs:simpleType>

	<xs:element name="salidaLong">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="longitudRangoType">
					<xs:attribute name="unidades" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="salidaLat">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="latitudRangoType">
					<xs:attribute name="unidades" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="salidaAlt">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="distanciaPositivaType">
					<xs:attribute name="unidades" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="llegadaLong">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="longitudRangoType">
					<xs:attribute name="unidades" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="llegadaLat">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="latitudRangoType">
					<xs:attribute name="unidades" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="llegadaAlt">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="distanciaPositivaType">
					<xs:attribute name="unidades" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<!-- Hitos -->
	<xs:element name="hitos">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="puertosMontaña" />
				<xs:element ref="Sprints" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="puertosMontaña">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="categoria1" />
				<xs:element ref="categoria3" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="categoria1">
		<xs:complexType>
			<xs:sequence minOccurs="1" maxOccurs="unbounded">
				<xs:element ref="montaña" />
				<xs:element ref="montañaLong" />
				<xs:element ref="montañaLat" />
				<xs:element ref="montañaAlt" />
				<xs:element ref="montañadist" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="categoria3">
		<xs:complexType>
			<xs:sequence minOccurs="1" maxOccurs="unbounded">
				<xs:element ref="montaña" />
				<xs:element ref="montañaLong" />
				<xs:element ref="montañaLat" />
				<xs:element ref="montañaAlt" />
				<xs:element ref="montañadist" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="montaña" type="xs:string" />
	<xs:element name="montañaLong">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="longitudRangoType">
					<xs:attribute name="unidades" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="montañaLat">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="latitudRangoType">
					<xs:attribute name="unidades" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="montañaAlt">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="distanciaPositivaType">
					<xs:attribute name="unidades" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="montañadist">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="distanciaPositivaType">
					<xs:attribute name="unidades" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="Sprints">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="intermedios" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="intermedios">
		<xs:complexType>
			<xs:sequence minOccurs="1" maxOccurs="unbounded">
				<xs:element ref="sprint" />
				<xs:element ref="sprintLong" />
				<xs:element ref="sprintLat" />
				<xs:element ref="sprintAlt" />
				<xs:element ref="sprintdist" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="sprint" type="xs:string" />
	<xs:element name="sprintLong">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="longitudRangoType">
					<xs:attribute name="unidades" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="sprintLat">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="latitudRangoType">
					<xs:attribute name="unidades" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="sprintAlt">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="distanciaPositivaType">
					<xs:attribute name="unidades" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="sprintdist">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="distanciaPositivaType">
					<xs:attribute name="unidades" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<!-- Puntos Anónimos -->
	<xs:element name="puntosAnonimos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="punto" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="punto">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="longitud" />
				<xs:element ref="latitud" />
				<xs:element ref="altitud" />
				<xs:element ref="distanciaPunto" />
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" />
		</xs:complexType>
	</xs:element>

	<xs:element name="longitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="longitudRangoType">
					<xs:attribute name="unidades" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="latitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="latitudRangoType">
					<xs:attribute name="unidades" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="altitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="distanciaPositivaType">
					<xs:attribute name="unidades" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="distanciaPunto">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="distanciaPositivaType">
					<xs:attribute name="unidades" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== EloyMariscalFernandez/sew/LaVuelta2026/xml/etapaEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>
<Etapa xmlns="http://www.uniovi.es"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.uniovi.es etapa.xsd">
    <nombre>Andorra la Vella a Andorra la Vella</nombre>
    <numero>4</numero>
    <datosCircuito>
        <distancia unidades="km">104.8</distancia>
        <fecha>2026-08-25</fecha>
        <desnivel unidades="m">2953</desnivel>
        <tipo>Montaña</tipo>
        <Empieza>Andorra la Vella</Empieza>
        <Acaba>Andorra la Vella</Acaba>
    </datosCircuito>
    <datosParticipantes>
        <tiempoGanador>PT2H40M35S</tiempoGanador>
        <velocidadMedia unidades="km/h">30.157</velocidadMedia>
        <lideresCarrera>
            <primero>Tadej Pogacar</primero>
            <segundo>Jarno Widar</segundo>
            <tercero>Felix Gall</tercero>
            <tiempoEntrePrimero-segundo>PT0H2M39S</tiempoEntrePrimero-segundo>
            <tiempoEntrePrimero-tercero>PT0H2M39S</tiempoEntrePrimero-tercero>
        </lideresCarrera>
        <lideresGeneral>
            <primero>Tadej Pogacar</primero>
            <segundo>Primož Roglič</segundo>
            <tercero>Enric Mas</tercero>
            <tiempoEntrePrimero-segundo>PT0H3M21S</tiempoEntrePrimero-segundo>
            <tiempoEntrePrimero-tercero>PT0H3M32S</tiempoEntrePrimero-tercero>
        </lideresGeneral>
        <lideresEquipos>
            <primero>UAE Team Emirates XRG </primero>
            <segundo> Decathlon CMA CGM Team</segundo>
            <tercero>Team Visma | Lease a Bike</tercero>
            <tiempoEntrePrimero-segundo>PT0H6M20S</tiempoEntrePrimero-segundo>
            <tiempoEntrePrimero-tercero>PT0H26M10S</tiempoEntrePrimero-tercero>
        </lideresEquipos>
    </datosParticipantes>
    <ReferenciasLocalidades> <!--Poner que sea solo "foto" "ref" etc -->       
        <ref>https://es.wikipedia.org/wiki/4.%C2%AA_etapa_de_la_Vuelta_a_Espa%C3%B1a_2026</ref>
        <ref>https://www.lavuelta.es/es/etapa-4</ref>
        <ref>https://www.rtve.es/deportes/20260824/vuelta-espana-2026-etapa-4-perfil-recorrido-hora-donde-ver-claves/17170465.shtml</ref>
    </ReferenciasLocalidades>
    <fotografias>
        <foto>recorrido.jpg</foto>
        <foto>montaña.jpg</foto>
    </fotografias>
    <videos>
        <video>resumen.mp4</video>
        <video>UltimosKM.mp4</video>
    </videos>
    <audios>
        <audio>entrevista.mp3</audio>
    </audios>
    <lugares>
        <salidaLong unidades="g">1.521750</salidaLong>
        <salidaLat unidades="g"> 42.505028 </salidaLat>
        <salidaAlt unidades="m"> 1.014</salidaAlt>
        <llegadaLong unidades="g"> 1.521750</llegadaLong>
        <llegadaLat unidades="g"> 42.505028</llegadaLat>
        <llegadaAlt unidades="m"> 1.014</llegadaAlt>
    </lugares>
    <hitos>
        <puertosMontaña>
            <categoria1>
                <montaña>Por D'envalira </montaña>
                <montañaLong unidades="g">1.719380</montañaLong>
                <montañaLat unidades="g">42.540180</montañaLat>
                <montañaAlt unidades="m">2.409</montañaAlt>
                <montañadist unidades="m">25.1</montañadist>
                <montaña>Collada de Beixalis </montaña>
                <montañaLong unidades="g">1.547910</montañaLong>
                <montañaLat unidades="g">42.527750</montañaLat>
                <montañaAlt unidades="m">1.803</montañaAlt>
                <montañadist unidades="m">59.3</montañadist>
                <montaña>Col de ordino </montaña>
                <montañaLong unidades="g">1.572205</montañaLong>
                <montañaLat unidades="g">42.556112</montañaLat>
                <montañaAlt unidades="m">1.989</montañaAlt>
                <montañadist unidades="m">78.7</montañadist>
            </categoria1>
            <categoria3>
                <montaña>La coella</montaña>
                <montañaLong unidades="g">1.531456</montañaLong>
                <montañaLat unidades="g">42.500705</montañaLat>
                <montañaAlt unidades="m">1.347</montañaAlt>
                <montañadist unidades="m">100</montañadist>
            </categoria3>
        </puertosMontaña>
        <Sprints>
            <intermedios>
                <sprint>Ordino</sprint>
                <sprintLong unidades="g">1.533190</sprintLong>
                <sprintLat unidades="g">42.556230</sprintLat>
                <sprintAlt unidades="m">1.296</sprintAlt>
                <sprintdist unidades="m">68.4</sprintdist>
            </intermedios>
        </Sprints>
    </hitos>
    <puntosAnonimos>
        <!-- Cambiar los puntos anonimos pa q se vean mejor, altitud dejarla igual-->
        <punto id="1">
            <longitud unidades="g">1.574800</longitud>
            <latitud unidades="g">42.539900</latitud>
            <altitud unidades="m">1260.000</altitud>
            <distanciaPunto unidades="km">2.800</distanciaPunto>
        </punto>
        <punto id="2">
            <longitud unidades="g">1.600700</longitud>
            <latitud unidades="g">42.547800</latitud>
            <altitud unidades="m">1380.000</altitud>
            <distanciaPunto unidades="km">4.300</distanciaPunto>
        </punto>
        <punto id="3">
            <longitud unidades="g">1.590640</longitud>
            <latitud unidades="g">42.553630</latitud>
            <altitud unidades="m">1479.000</altitud>
            <distanciaPunto unidades="km">5.100</distanciaPunto>
        </punto>
        <punto id="4">
            <longitud unidades="g">1.593660</longitud>
            <latitud unidades="g">42.560560</latitud>
            <altitud unidades="m">1578.000</altitud>
            <distanciaPunto unidades="km">6.000</distanciaPunto>
        </punto>
        <punto id="5">
            <longitud unidades="g">1.625800</longitud>
            <latitud unidades="g">42.579700</latitud>
            <altitud unidades="m">1600.000</altitud>
            <distanciaPunto unidades="km">10.200</distanciaPunto>
        </punto>
        <punto id="6">
            <longitud unidades="g">1.649700</longitud>
            <latitud unidades="g">42.580330</latitud>
            <altitud unidades="m">1710.000</altitud>
            <distanciaPunto unidades="km">13.200</distanciaPunto>
        </punto>
        <punto id="7">
            <longitud unidades="g">1.658900</longitud>
            <latitud unidades="g">42.578400</latitud>
            <altitud unidades="m">1770.000</altitud>
            <distanciaPunto unidades="km">14.400</distanciaPunto>
        </punto>
        <punto id="8">
            <longitud unidades="g">1.680900</longitud>
            <latitud unidades="g">42.567800</latitud>
            <altitud unidades="m">1900.000</altitud>
            <distanciaPunto unidades="km">18.000</distanciaPunto>
        </punto>
        <punto id="9">
            <longitud unidades="g">1.684900</longitud>
            <latitud unidades="g">42.559970</latitud>
            <altitud unidades="m">2003.000</altitud>
            <distanciaPunto unidades="km">20.200</distanciaPunto>
        </punto>
        <punto id="10">
            <longitud unidades="g">1.701320</longitud>
            <latitud unidades="g">42.532270</latitud>
            <altitud unidades="m">2130.000</altitud>
            <distanciaPunto unidades="km">23.000</distanciaPunto>
        </punto>
        <punto id="11">
            <longitud unidades="g">1.727900</longitud>
            <latitud unidades="g">42.542300</latitud>
            <altitud unidades="m">2220.000</altitud>
            <distanciaPunto unidades="km">27.000</distanciaPunto>
        </punto>
        <punto id="12">
            <longitud unidades="g">1.726000</longitud>
            <latitud unidades="g">42.537600</latitud>
            <altitud unidades="m">2010.000</altitud>
            <distanciaPunto unidades="km">31.100</distanciaPunto>
        </punto>
        <punto id="13">
            <longitud unidades="g">1.707500</longitud>
            <latitud unidades="g">42.552300</latitud>
            <altitud unidades="m">1850.000</altitud>
            <distanciaPunto unidades="km">34.000</distanciaPunto>
        </punto>
        <punto id="14">
            <longitud unidades="g">1.683200</longitud>
            <latitud unidades="g">42.570800</latitud>
            <altitud unidades="m">1850.000</altitud>
            <distanciaPunto unidades="km">36.800</distanciaPunto>
        </punto>
        <punto id="15">
            <longitud unidades="g">1.649700</longitud>
            <latitud unidades="g">42.580330</latitud>
            <altitud unidades="m">1710.000</altitud>
            <distanciaPunto unidades="km">41.000</distanciaPunto>
        </punto>
        <punto id="16">
            <longitud unidades="g">1.658300</longitud>
            <latitud unidades="g">42.583300</latitud>
            <altitud unidades="m">1510.000</altitud>
            <distanciaPunto unidades="km">46.000</distanciaPunto>
        </punto>
        <punto id="17">
            <longitud unidades="g">1.612800</longitud>
            <latitud unidades="g">42.555400</latitud>
            <altitud unidades="m">1350.000</altitud>
            <distanciaPunto unidades="km">48.500</distanciaPunto>
        </punto>
        <punto id="18">
            <longitud unidades="g">1.571900</longitud>
            <latitud unidades="g">42.532700</latitud>
            <altitud unidades="m">1280.000</altitud>
            <distanciaPunto unidades="km">52.100</distanciaPunto>
        </punto>
        <punto id="19">
            <longitud unidades="g">1.562900</longitud>
            <latitud unidades="g">42.532700</latitud>
            <altitud unidades="m">1330.000</altitud>
            <distanciaPunto unidades="km">54.400</distanciaPunto>
        </punto>
        <punto id="20">
